# Generated by Django 2.0 on 2017-12-16 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icnum', models.CharField(max_length=12, unique=True)),
                ('name', models.TextField()),
                ('course', models.CharField(choices=[('PR', 'Programming'), ('NT', 'Networking'), ('PC', 'PC Technichian')], default='PC', max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cretedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
