# Generated by Django 2.0 on 2017-12-19 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20171219_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cretedby',
            new_name='createdby',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('PR', 'Programming'), ('NT', 'Networking'), ('PC', 'PC Technichian')], default='PC', max_length=2, verbose_name='Courserwork'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='icnum',
            field=models.CharField(max_length=12, unique=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
    ]
